name: super_editor_quill_example
description: "Demonstrates how to use the super_editor_quill plugin."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  js:
  super_editor_quill:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  super_editor:
    path: ../../super_editor

flutter:
  uses-material-design: true
